import {
  ArrowLeftRight,
  ClipboardList,
  Database,
  FileCheck,
  FileText,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Receipt,
  ShoppingCart,
  Users,
  Wallet,
} from "lucide-react";
import type { IRoute } from "../models/common/route.model";
import { permissionLoader } from "./route.guard";
import { lazyView } from "./route.lazy";

export const protectedViewsRoutes: IRoute[] = [
  {
    key: "dashboard",
    path: "/",
    label: "Dashboard",
    description: "Company-wide financial standing and alerts",
    icon: LayoutDashboard,
    group: "Main",
    can: "viewDashboard",
    loader: permissionLoader("viewDashboard", "/transactions"),
    ...lazyView(() => import("../pages/Dashboard/DashboardView")),
  },
  {
    key: "transactions",
    path: "/transactions",
    label: "Transactions",
    description: "Sales, payments, deposits and collections",
    icon: ArrowLeftRight,
    group: "Operations",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Transactions/TransactionsView")),
  },
  {
    key: "sales",
    path: "/sales",
    label: "Sales",
    description: "Sales, deposits and admin verification",
    icon: Receipt,
    group: "Operations",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Sales/SalesView")),
  },
  {
    key: "purchases",
    path: "/purchases",
    label: "Purchases",
    description: "Goods bought, each with an auto-generated voucher",
    icon: ShoppingCart,
    group: "Operations",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Purchases/PurchasesView")),
  },
  {
    key: "expenses",
    path: "/expenses",
    label: "Expenses",
    description: "Operating costs, each with an auto-generated voucher",
    icon: Wallet,
    group: "Operations",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Expenses/ExpensesView")),
  },
  {
    key: "vouchers",
    path: "/vouchers",
    label: "Vouchers",
    description: "Approval workflow for check and cash vouchers",
    icon: FileText,
    group: "Operations",
    can: "createVouchers",
    ...lazyView(() => import("../pages/Vouchers/VouchersView")),
  },
  {
    key: "receivables",
    path: "/receivables",
    label: "Receivables",
    description: "Amounts customers owe the business",
    icon: ClipboardList,
    group: "Accounting",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Receivables/ReceivablesView")),
  },
  {
    key: "payables",
    path: "/payables",
    label: "Payables",
    description: "Amounts the business owes suppliers",
    icon: FileCheck,
    group: "Accounting",
    can: "viewReminders",
    ...lazyView(() => import("../pages/Payables/PayablesView")),
  },
  {
    key: "reports",
    path: "/reports",
    label: "Reports",
    description: "Daily, weekly, monthly, cash flow and ledger reports",
    icon: Landmark,
    group: "Monitoring",
    can: "viewIncomeExpenses",
    loader: permissionLoader("viewIncomeExpenses", "/transactions"),
    ...lazyView(() => import("../pages/Reports/ReportsView")),
  },
  {
    key: "branches",
    path: "/branches",
    label: "Branch Monitoring",
    description: "Add, rename and monitor every business unit",
    icon: LayoutGrid,
    group: "Monitoring",
    can: "viewBranchMonitoring",
    loader: permissionLoader("viewBranchMonitoring", "/"),
    ...lazyView(() => import("../pages/Branches/BranchesView")),
  },
  {
    key: "master-data",
    path: "/master-data",
    label: "Master Data",
    description: "Suppliers and expense categories",
    icon: Database,
    group: "System",
    can: "manageMasterData",
    loader: permissionLoader("manageMasterData", "/"),
    ...lazyView(() => import("../pages/MasterData/MasterDataView")),
  },
  {
    key: "users",
    path: "/users",
    label: "Users",
    description: "Accounts, roles and branch access",
    icon: Users,
    group: "System",
    can: "manageUsers",
    loader: permissionLoader("manageUsers", "/"),
    ...lazyView(() => import("../pages/Users/UsersView")),
  },
];
