import { chromium } from "playwright-core";
const base = "http://localhost:4199";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const P = await ctx.newPage();
const log = (...a) => console.log(...a);
P.on("pageerror", (e) => log("pageerror", e.message.slice(0, 150)));
const signIn = async (u) => {
  await P.goto(`${base}/`, { waitUntil: "networkidle" });
  await P.getByLabel("Email").fill(`${u}@qa.test`); await P.getByLabel("Password").fill("QaTest#2026");
  await P.locator("button[type=submit]").click(); await P.waitForTimeout(6000);
};
const signOut = async () => {
  await P.locator("header button:has([data-slot=avatar])").first().click(); await P.waitForTimeout(600);
  await P.locator("[role=menuitem]", { hasText: "Sign out" }).click(); await P.waitForTimeout(3000);
};
const queue = () => P.evaluate(() => { const s = JSON.parse(localStorage.getItem("tartar-sync-queue") || "{}").state || {}; return { q: (s.queue || []).map((w) => w.label + "@" + String(w.owner).slice(0, 4)), f: (s.failed || []).map((x) => x.write.label) }; });
const sales = async () => { await P.goto(`${base}/sales`, { waitUntil: "networkidle" }); await P.getByRole("button", { name: "Record sale" }).first().waitFor({ timeout: 20000 }); await P.waitForTimeout(2500); };
await signIn("qaemp1"); await sales();
await ctx.setOffline(true); await P.waitForTimeout(800);
await P.getByRole("button", { name: "Record sale" }).first().click(); await P.waitForTimeout(800);
await P.locator("[role=dialog] [name=amount]").fill("953");
await P.getByRole("combobox", { name: "Cash account" }).last().click(); await P.waitForTimeout(500);
await P.locator("[role=option]").filter({ hasText: "Cash Drawer" }).first().click(); await P.waitForTimeout(300);
await P.locator("[role=dialog]").last().getByRole("button", { name: "Record", exact: true }).click(); await P.waitForTimeout(2500);
log("emp1 offline queued:", JSON.stringify(await queue()));
await signOut().catch((e) => log("signout offline failed:", e.message.slice(0, 80)));
log("after offline sign-out url:", P.url(), JSON.stringify(await queue()));
await ctx.setOffline(false); await P.waitForTimeout(2000);
await signIn("qaemp2"); await sales();
log("emp2 signed in, storage:", JSON.stringify(await queue()));
log("emp2 sees 953 pending row?", await P.locator("tbody tr", { hasText: "953" }).count());
const syncBtn = P.locator("header button[aria-label*=sync i], header button[aria-label*=saved i], header button[aria-label*=Offline]").first();
log("emp2 sync button:", await syncBtn.getAttribute("aria-label"), "| badge:", JSON.stringify(await syncBtn.innerText()));
await syncBtn.click(); await P.waitForTimeout(800);
log("emp2 sync panel:", (await P.locator("[role=dialog][aria-label=\"Sync status\"]").innerText()).split(String.fromCharCode(10)).join(" | "));
await P.screenshot({ path: "shots/drive/c4-emp2-panel.png" }); await P.keyboard.press("Escape");
await P.waitForTimeout(8000);
log("emp2 after 8s:", JSON.stringify(await queue()));
await signOut(); await signIn("qaemp1"); await sales(); await P.waitForTimeout(10000);
log("emp1 back:", JSON.stringify(await queue()));
await sales();
log("953 listed for emp1:", await P.locator("tbody tr", { hasText: "953" }).count());
await browser.close();
