import { login, get, rpc, req } from "./rest.mjs";
const uuid = () => crypto.randomUUID();
const [e1, e2, a1, a2] = await Promise.all(["qaemp1", "qaemp2", "qaadmin1", "qaadmin2"].map(login));
const sum = (rs) => { const by = {}; rs.forEach((r) => { const k = `${r.status} ${r.status >= 300 ? (JSON.parse(r.body || "{}").message ?? r.body).slice(0, 70) : "ok"}`; by[k] = (by[k] ?? 0) + 1; }); return by; };
const log = (t, v) => console.log(t.padEnd(46), JSON.stringify(v));
const today = "2026-10-01", cust = "e257fb9a-cc2c-4bae-a85c-193b0075d425";
const sample = (await get(`receivables?select=*&id=eq.3b9c528e-1d30-439d-8c00-db48873fafe3`, a1.token))[0];
log("receivable cols", Object.keys(sample));
const mk = async (amt) => { const id = uuid(); const { id: _i, created_at, paid_amount, status, ...rest } = sample; const r = await req("POST", "receivables", { ...rest, id, amount: amt, paid_amount: 0, reference_number: "C-RACE-" + amt + "-" + id.slice(0,4) }, a1.token); if (r.status >= 300) log("mk fail", r); return id; };
const pay = (u, rid, amt) => rpc("record_ledger_payment", { p_idempotency_key: uuid(), p_kind: "receivable", p_party_id: cust, p_party_name: "QA Customer A", p_amount: amt, p_paid_at: today, p_reference_number: null, p_allocations: [{ ledger_id: rid, amount: amt }], p_created_by: u.id }, u.token);
const r1 = await mk(1000);
log("R5 4 users pay 600 of 1000 parallel", sum(await Promise.all([pay(e1, r1, 600), pay(e2, r1, 600), pay(a1, r1, 600), pay(a2, r1, 600)])));
log("  after", await get(`receivables?select=paid_amount,status&id=eq.${r1}`, a1.token));
const r2 = await mk(1000);
const ep = JSON.parse((await pay(e1, r2, 700)).body);
log("R8 emp pending 700, then admin pays 300 + verify race", "");
const [adm, ver] = await Promise.all([pay(a1, r2, 300), rpc("verify_payment", { p_idempotency_key: uuid(), p_payment_id: ep }, a2.token)]);
log("  admin pay 300 / verify emp 700", sum([adm, ver]));
log("  after", await get(`receivables?select=paid_amount,status&id=eq.${r2}`, a1.token));
log("  admin pays 1 more (must refuse)", sum([await pay(a2, r2, 1)]));
const r3 = await mk(500);
const p1 = JSON.parse((await pay(e1, r3, 500)).body);
log("R9 verify + reject same pending payment parallel", sum(await Promise.all([rpc("verify_payment", { p_idempotency_key: uuid(), p_payment_id: p1 }, a1.token), rpc("reject_payment", { p_idempotency_key: uuid(), p_payment_id: p1 }, a2.token), rpc("verify_payment", { p_idempotency_key: uuid(), p_payment_id: p1 }, a2.token)])));
log("  after", await get(`receivables?select=paid_amount,status&id=eq.${r3}`, a1.token), await get(`payments?select=status&id=eq.${p1}`, a1.token));
console.log("rcv ids", r1, r2, r3);
