import { chromium } from "playwright-core";
const base = "http://localhost:4199";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const A = await ctx.newPage();
const log = (...a) => console.log(...a);
await A.goto(`${base}/`, { waitUntil: "networkidle" });
await A.getByLabel("Email").fill("qaemp1@qa.test");
await A.getByLabel("Password").fill("QaTest#2026");
await A.locator("button[type=submit]").click();
await A.waitForURL((u) => !/\/login$/.test(u.pathname), { timeout: 15000 }); await A.waitForTimeout(5000);
await A.goto(`${base}/sales`, { waitUntil: "networkidle" }); await A.getByRole("button", { name: "Record sale" }).first().waitFor({ timeout: 30000 });
const B = await ctx.newPage();
await B.goto(`${base}/sales`, { waitUntil: "networkidle" }); await B.getByRole("button", { name: "Record sale" }).first().waitFor({ timeout: 30000 });
const queue = (p) => p.evaluate(() => { const s = JSON.parse(localStorage.getItem("tartar-sync-queue") || "{}").state || {}; return { q: (s.queue || []).map((w) => w.label), f: (s.failed || []).map((x) => x.write.label + " => " + x.reason) }; });
const sale = async (p, amt) => {
  await p.bringToFront();
  await p.getByRole("button", { name: "Record sale" }).first().click();
  await p.waitForTimeout(800);
  await p.locator("[role=dialog] [name=amount]").fill(amt);
  const box = p.getByRole("combobox", { name: "Cash account" }).last(); await box.click(); await p.waitForTimeout(500);
  await p.locator("[role=option]").filter({ hasText: "Cash Drawer" }).first().click(); await p.waitForTimeout(300);
  await p.locator("[role=dialog]").last().getByRole("button", { name: "Record", exact: true }).click();
  await p.waitForTimeout(2500);
};
await ctx.setOffline(true); await A.waitForTimeout(1000);
await sale(A, "944");
log("after A 931  A:", JSON.stringify(await queue(A)));
await sale(B, "945");
log("after B 932  B-view storage:", JSON.stringify(await queue(B)));
await sale(A, "946");
log("after A 933  storage:", JSON.stringify(await queue(A)));
log("B in-memory tab count of pending rows:", await B.locator("tbody tr", { hasText: "Pending" }).count(), " A:", await A.locator("tbody tr", { hasText: "Pending" }).count());
await B.close(); log("closed tab B (offline)"); await A.reload(); await A.waitForTimeout(3000); log("after A reload storage:", JSON.stringify(await queue(A)));
await ctx.setOffline(false);
await A.waitForTimeout(15000);
log("after online storage:", JSON.stringify(await queue(A)));
await A.goto(`${base}/sales`, { waitUntil: "networkidle" }); await A.waitForTimeout(6000);
log("listed:", (await A.locator("tbody tr").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).filter((t) => /94[4-8]/.test(t)).join(" || "));
const B2 = await ctx.newPage();
await B2.goto(`${base}/sales`, { waitUntil: "networkidle" }); await B2.getByRole("button", { name: "Record sale" }).first().waitFor({ timeout: 30000 });
await ctx.setOffline(true); await A.waitForTimeout(1000);
await sale(A, "947");
await sale(B2, "948");
log("two tabs offline storage:", JSON.stringify(await queue(A)), " B2 view:", JSON.stringify(await queue(B2)));
await ctx.setOffline(false);
await A.waitForTimeout(15000);
log("after both reconnect A:", JSON.stringify(await queue(A)), " B2:", JSON.stringify(await queue(B2)));
await A.goto(`${base}/sales`, { waitUntil: "networkidle" }); await A.waitForTimeout(6000);
log("listed 2:", (await A.locator("tbody tr").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).filter((t) => /94[4-8]/.test(t)).join(" || "));
await browser.close();
